CREATE TABLE person (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstName VARCHAR(255) NOT NULL,
    lastName CLOB,
    age INTEGER,
    url VARCHAR(450) UNIQUE NOT NULL,
    height DOUBLE DEFAULT 62.3,
    companyID BIGINT,
    cool SMALLINT(1) DEFAULT 1,
    modified DATETIME,
    weight DOUBLE,
    typeOfPerson VARCHAR(30),
    CONSTRAINT fk_person_companyid FOREIGN KEY (companyID) REFERENCES company(id),
    PRIMARY KEY(id)
)
